### ISSUE TITLE
High score lookup throws 500 error

### ISSUE THREAD

**Issue by adammccartney** [AustrianDataLAB/pacman#6]
# Description

If client requests high score table, server responds with 500 error. This occurs after deploying the application to a freshly installed cluster with the "buildsystem" profile. 
  - [X] Check if initial connection to db successful
    - It succeeds, see console log at startup.
  - [X] Check if helm chart works
    - It is not working, doesn't add an [[id:25ea03fd-3dfe-49ce-9689-079571b4a300][ingress]].
  - [X] Can you get the high score using curl?
    - No, the following error is returned by the client
```bash
<x@y> (main *) curl http://ingress-u-4u5fec6ftd.caas-0005.dev.austrianopencloudcommunity.org/highscores/list
<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/style.css"></head><body><h1>db.collection is not a function</h1><h2></h2><pre>TypeError: db.collection is not a function
    at /usr/src/app/routes/highscores.js:23:22
    at Database.getDb (/usr/src/app/lib/database.js:36:13)
    at /usr/src/app/routes/highscores.js:17:14
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at urlencodedParser (/usr/src/app/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)</pre></body></html>
```

- [x] Debug `Type Error: db.connection is not a function`
    - [x] Is the db running? yes, see point above about the initial connection success.
    - [x] Does the database, loaded as `config.database.url` exist?
      -  this variable currently resolves as: "mongodb://blinky:pinky@mongo:27017/pacman"
      -  querying the mongodb API within the mongo container reveals that there are 0 databases.
    - [x] Does the the "highscore" collection exist?

**Comment by adammccartney** [comment]
Okay, so I'm starting to understand the problem a bit better.

The original deployment contained an initContainers block, that started as root and changed the permissions of the `/bitnami/mongodb`. The original can be seen here: https://github.com/saintdle/pacman-tanzu/blob/841d7ff7e6343c65d1dd5b4b92ae181ac937305d/deployments/mongo-deployment.yaml#L19
Running any container as root is a violation of security policy.

So... the "solution" to this was to simply remove the `initContainers` block. This allowed us to start the app and play it in the client. It even shows the initial connection to the db. Where it subtly fails is when the application running pacman (1001:1001) tries to write to the volume, which now has the current set of permissions:

```bash
I have no name!@mongo-5c48b99889-jcg5t:/$ ls -lah bitnami/mongodb
total 24K
drwxrwsr-x. 4 root users 4.0K Dec 20 09:17 .
drwxr-xr-x. 3 root root    21 Jun 14  2022 ..
drwxr-sr-x. 3 1001 users 4.0K Dec 20 09:17 data
drwxrws---. 2 root users  16K Dec 20 09:17 lost+found
```

### Required solution

We need someway to do the equivalent of `chown -R 1001:1001 /bitnami/mongodb` without being root.

**Comment by adammccartney** [comment]
### Attempt 1
```yaml
spec:
    ...
    securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
```
*Result*: enters `crashLoopBackOff`

### Attempt 2
```yaml
spec:
    ...
    securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 1001
```
*Result*: allows start up, seems to establish pacman db with the user. 
Execute an interactive shell in the pod:
+ Run the `mongo; use pacman; db.auth("$user", "$pass")`. 
   - Command succeeds. 
+ Run command `show collections`. 
   - Does not return any collections.

**Comment by adammccartney** [comment]
It kind of smells like it might be something to do with an API change within the javascript libraries used.

Mongo db deployment is using `bitnami/mognodb: 4.4.14`
`package.json` requires `"mongodb": "^4.5.0"`

**Comment by adammccartney** [comment]
Okay, so the original repository packages an image,
`     - image: quay.io/ifont/pacman-nodejs-app:latest`

this appears to reference the repo: https://github.com/font/pacman,
whose package manifest uses `    "mongodb": "^2.2.24"`
     

This was changed by @entlein in Commit 9c232e04
https://gitlab.tuwien.ac.at/ADLS/services-k8s/pacman/-/commit/9c232e04204703adc6d9677f18e5ea16ee24d713
This is likely to have introduced the breaking changes.

**Comment by adammccartney** [comment]
Here is the documentation on upgrading to version 4.x:
https://github.com/mongodb/node-mongodb-native/blob/HEAD/etc/notes/CHANGES_4.0.0.md

### Proposed solution
1. Check that the version 4.x api allows us to do what we want (use a node session in a running pod). 
2. If necessary upgrade the parts of the pacman source that use the mongodb driver.

**Comment by adammccartney** [comment]
See: https://stackoverflow.com/a/47974041/15278522

The code in the `lib/database.js` file relies on the old version of the api, where a `MongoClient` is expected to return a database instance. This is no longer the case, as of the new (Version 3) API, MongoClient Returns a `client` object, which contains a `db` function that can be called (with the name of the database). This will (hopefully) return the desired instance.
